=== se-sic/vara-feature/test/vm.dtd
<!ELEMENT vm (binaryOptions, numericOptions?, booleanConstraints?, nonBooleanConstraints?, mixedConstraints?)>
<!ATTLIST vm name CDATA #REQUIRED root CDATA #IMPLIED>
<!ELEMENT binaryOptions (configurationOption*)>
<!ELEMENT numericOptions (configurationOption*)>
<!ELEMENT booleanConstraints (constraint*)>
<!ELEMENT nonBooleanConstraints (constraint*)>
<!ELEMENT mixedConstraints (constraint*)>
<!ELEMENT configurationOption (name, outputString?, (prefix | preFix)?, (postfix | postFix)?, parent?, children?, impliedOptions?, excludedOptions?, defaultValue?, optional?, ((minValue, maxValue) | values)?, stepFunction?, location?)>
<!ELEMENT constraint (#PCDATA)>
<!ATTLIST constraint req CDATA #IMPLIED exprKind CDATA #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT outputString (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT preFix (#PCDATA)>
<!ELEMENT postfix (#PCDATA)>
<!ELEMENT postFix (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT children (options*)>
<!ELEMENT impliedOptions (options*)>
<!ELEMENT excludedOptions (options*)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT options (#PCDATA)>
<!ELEMENT optional (#PCDATA)>
<!ELEMENT minValue (#PCDATA)>
<!ELEMENT maxValue (#PCDATA)>
<!ELEMENT values (#PCDATA)>
<!ELEMENT stepFunction (#PCDATA)>
<!ELEMENT location (path, start?, end?)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT start (line, column)>
<!ELEMENT end (line, column)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT column (#PCDATA)>

=== se-sic/vara-feature/bindings/python/tests/TEST_INPUTS/simple_example_feature_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="Children" root="test/path/to/root/">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <children>
        <options>A</options>
        <options>B</options>
        <options>C</options>
      </children>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>C</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
  <booleanConstraints/>
</vm>

=== se-sic/vara-feature/bindings/python/tests/TEST_INPUTS/simple_example_feature_model_merge.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="Children" root="test/path/to/root/">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <children>
        <options>X</options>
        <options>Y</options>
        <options>Z</options>
      </children>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>X</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>Y</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>Z</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
</vm>

=== se-sic/vara-feature/bindings/python/tests/TEST_INPUTS/example_feature_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="ABC" root="test/path/to/root/" commit="DABAD00">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <children>
        <options>A</options>
        <options>B</options>
        <options>C</options>
      </children>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <children>
        <options>AA</options>
        <options>AB</options>
        <options>AC</options>
      </children>
      <optional>False</optional>
      <locations>
        <sourceRange>
          <path>main.c</path>
          <start>
            <line>6</line>
            <column>3</column>
          </start>
          <end>
            <line>6</line>
            <column>26</column>
          </end>
        </sourceRange>
      </locations>
    </configurationOption>
    <configurationOption>
      <name>AA</name>
      <parent>A</parent>
      <excludedOptions>
        <options>AC</options>
        <options>C</options>
      </excludedOptions>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>AB</name>
      <parent>A</parent>
      <excludedOptions>
        <options>AC</options>
      </excludedOptions>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>AC</name>
      <parent>A</parent>
      <excludedOptions>
        <options>AB</options>
      </excludedOptions>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <children>
        <options>N</options>
      </children>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>C</name>
      <parent>root</parent>
      <excludedOptions>
        <options>AA</options>
      </excludedOptions>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions>
    <configurationOption>
      <name>N</name>
      <parent>B</parent>
      <optional>True</optional>
      <values>1;5;9</values>
    </configurationOption>
  </numericOptions>
  <booleanConstraints/>
</vm>

=== se-sic/vara-feature/test/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="ABC" root="test">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>False</optional>
      <location>
        <path>main.c</path>
        <start>
          <line>6</line>
          <col>3</col>
        </start>
        <end>
          <line>6</line>
          <col>26</col>
        </end>
      </location>
    </configurationOption>
    <configurationOption>
      <name>AA</name>
      <parent>A</parent>
      <excludedOptions>
        <options>AC</options>
        <options>C</options>
      </excludedOptions>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>AB</name>
      <parent>A</parent>
      <excludedOptions>
        <options>AC</options>
      </excludedOptions>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>AC</name>
      <parent>A</parent>
      <excludedOptions>
        <options>AA</options>
        <options>AB</options>
      </excludedOptions>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>C</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions>
    <configurationOption>
      <name>N</name>
      <parent>B</parent>
      <optional>True</optional>
      <values>1;5;9</values>
    </configurationOption>
  </numericOptions>
  <booleanConstraints>
    <constraint>!N | C</constraint>
    <constraint>!AA | !AB</constraint>
    <constraint>!AB | B</constraint>
    <constraint>!B | AB</constraint>
    <constraint>AB | AC | AA</constraint>
  </booleanConstraints>
</vm>
