=== se-sic/vara-feature/unittests/resources/xml/vm.dtd
<!ELEMENT vm (binaryOptions, numericOptions?, booleanConstraints?, nonBooleanConstraints?, mixedConstraints?)>
<!ATTLIST vm name CDATA #REQUIRED root CDATA #IMPLIED commit CDATA #IMPLIED>
<!ELEMENT binaryOptions (configurationOption*)>
<!ELEMENT numericOptions (configurationOption*)>
<!ELEMENT booleanConstraints (constraint*)>
<!ELEMENT nonBooleanConstraints (constraint*)>
<!ELEMENT mixedConstraints (constraint*)>
<!ELEMENT configurationOption (name, outputString?, (prefix | preFix)?, (postfix | postFix)?, parent?, children?, impliedOptions?, excludedOptions?, optional?, ((minValue, maxValue) | values)?, stepFunction?, defaultValue?, locations?)>
<!ELEMENT constraint (#PCDATA)>
<!ATTLIST constraint req CDATA #IMPLIED exprKind CDATA #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT outputString (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT preFix (#PCDATA)>
<!ELEMENT postfix (#PCDATA)>
<!ELEMENT postFix (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT children (options*)>
<!ELEMENT impliedOptions (options*)>
<!ELEMENT excludedOptions (options*)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT options (#PCDATA)>
<!ELEMENT optional (#PCDATA)>
<!ELEMENT minValue (#PCDATA)>
<!ELEMENT maxValue (#PCDATA)>
<!ELEMENT values (#PCDATA)>
<!ELEMENT stepFunction (#PCDATA)>
<!ELEMENT locations (sourceRange*)>
<!ELEMENT sourceRange (revisionRange?, path, start, end, memberOffset?)>
<!ATTLIST sourceRange category (necessary|inessential) "necessary">
<!ELEMENT revisionRange (introduced, removed?)>
<!ELEMENT introduced (#PCDATA)>
<!ELEMENT removed (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT start (line, column)>
<!ELEMENT end (line, column)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT column (#PCDATA)>
<!ELEMENT memberOffset (#PCDATA)>

=== se-sic/vara-feature/unittests/resources/xml/test_only_parents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="Children" root="test">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>C</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CA</name>
      <parent>C</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CB</name>
      <parent>C</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CC</name>
      <parent>C</parent>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
  <booleanConstraints/>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_constraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="AB" root="test">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <children>
        <options>A</options>
        <options>B</options>
      </children>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>False</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions>
    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <optional>False</optional>
      <minValue>0</minValue>
      <maxValue>100</maxValue>
    </configurationOption>
  </numericOptions>
  <booleanConstraints>
    <constraint>(A | B)</constraint>
  </booleanConstraints>
  <nonBooleanConstraints>
    <constraint>(A + B)</constraint>
  </nonBooleanConstraints>
  <mixedConstraints>
    <constraint req="all" exprKind="pos">((A * B) = 0)</constraint>
  </mixedConstraints>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_three_optional_features.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="SingleLocalSingle" root="root">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <parent></parent>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <outputString>A</outputString>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <outputString>B</outputString>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>C</name>
      <outputString>C</outputString>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_numbers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="ABC" root="test">
  <binaryOptions>

    <configurationOption>
      <name>root</name>
      <children>
        <options>A</options>
        <options>B</options>
        <options>C</options>
      </children>
      <optional>False</optional>
    </configurationOption>

  </binaryOptions>
  <numericOptions>

    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>True</optional>
      <minValue>-9223372036854775809</minValue>
      <maxValue>9223372036854775808</maxValue>
    </configurationOption>

    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <optional>True</optional>
      <values>-9223372036854775809;0;9223372036854775808</values>
    </configurationOption>

    <configurationOption>
      <name>C</name>
      <parent>root</parent>
      <optional>True</optional>
      <minValue>2e-06</minValue>
      <maxValue>4e+3</maxValue>
    </configurationOption>

  </numericOptions>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_output_string.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="Test" root="test">
  <binaryOptions>
    <configurationOption>
      <name>A</name>
      <outputString>-a</outputString>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
  <booleanConstraints/>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="Children" root="test">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <children>
        <options>A</options>
        <options>B</options>
        <options>C</options>
      </children>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>True</optional>
      <locations>
        <sourceRange>
          <path>path/test.c</path>
          <start>
            <line>24</line>
            <column>1337</column>
          </start>
          <end>
            <line>42</line>
            <column>7331</column>
          </end>
        </sourceRange>
        <sourceRange>
          <path>path/test.c</path>
          <start>
            <line>24</line>
            <column>1337</column>
          </start>
          <end>
            <line>42</line>
            <column>7331</column>
          </end>
        </sourceRange>
      </locations>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>C</name>
      <parent>root</parent>
      <children>
        <options>CA</options>
        <options>CB</options>
        <options>CC</options>
      </children>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CA</name>
      <parent>C</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CB</name>
      <parent>C</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CC</name>
      <parent>C</parent>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
  <booleanConstraints/>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_msmr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="SingleLocalSingle" root="root">
    <binaryOptions>
        <configurationOption>
            <name>root</name>
            <parent></parent>
            <optional>False</optional>
        </configurationOption>
        <configurationOption>
            <name>Slow</name>
            <outputString>--slow</outputString>
            <parent>root</parent>
            <optional>True</optional>
        </configurationOption>
        <configurationOption>
            <name>Header</name>
            <outputString>--header</outputString>
            <parent>root</parent>
            <optional>True</optional>
        </configurationOption>
        <configurationOption>
            <name>Extern</name>
            <outputString>--extern</outputString>
            <parent>root</parent>
            <optional>True</optional>
            <locations>
                <sourceRange category="necessary">
                    <path>src/MultiSharedMultipleRegions/FeatureHeader.cpp</path>
                    <start>
                        <line>3</line>
                        <column>6</column>
                    </start>
                    <end>
                        <line>3</line>
                        <column>18</column>
                    </end>
                </sourceRange>
            </locations>
        </configurationOption>
        <configurationOption>
            <name>Cpp</name>
            <outputString>--cpp</outputString>
            <parent>root</parent>
            <optional>True</optional>
        </configurationOption>
    </binaryOptions>
</vm>
