=== se-sic/vara-feature/unittests/resources/xml/vm.dtd
<!ELEMENT vm (binaryOptions, numericOptions?, booleanConstraints?, nonBooleanConstraints?, mixedConstraints?)>
<!ATTLIST vm name CDATA #REQUIRED root CDATA #IMPLIED commit CDATA #IMPLIED>
<!ELEMENT binaryOptions (configurationOption*)>
<!ELEMENT numericOptions (configurationOption*)>
<!ELEMENT booleanConstraints (constraint*)>
<!ELEMENT nonBooleanConstraints (constraint*)>
<!ELEMENT mixedConstraints (constraint*)>
<!ELEMENT configurationOption (name, outputString?, (prefix | preFix)?, (postfix | postFix)?, parent?, children?, impliedOptions?, excludedOptions?, optional?, ((minValue, maxValue) | values)?, stepFunction?, defaultValue?, locations?)>
<!ELEMENT constraint (#PCDATA)>
<!ATTLIST constraint req CDATA #IMPLIED exprKind CDATA #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT outputString (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT preFix (#PCDATA)>
<!ELEMENT postfix (#PCDATA)>
<!ELEMENT postFix (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT children (options*)>
<!ELEMENT impliedOptions (options*)>
<!ELEMENT excludedOptions (options*)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT options (#PCDATA)>
<!ELEMENT optional (#PCDATA)>
<!ELEMENT minValue (#PCDATA)>
<!ELEMENT maxValue (#PCDATA)>
<!ELEMENT values (#PCDATA)>
<!ELEMENT stepFunction (#PCDATA)>
<!ELEMENT locations (sourceRange*)>
<!ELEMENT sourceRange (revisionRange?, path, start, end, memberOffset?)>
<!ATTLIST sourceRange category (necessary|inessential) "necessary">
<!ELEMENT revisionRange (introduced, removed?)>
<!ELEMENT introduced (#PCDATA)>
<!ELEMENT removed (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT start (line, column)>
<!ELEMENT end (line, column)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT column (#PCDATA)>
<!ELEMENT memberOffset (#PCDATA)>

=== se-sic/vara-feature/unittests/resources/xml/test_step_function.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="ABC" root="test">
  <binaryOptions>
  </binaryOptions>
  <numericOptions>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>True</optional>
      <minValue>0</minValue>
      <maxValue>100</maxValue>
      <stepFunction>x + 42</stepFunction>
    </configurationOption>
  </numericOptions>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_revision_range.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="Children" root="test">
  <binaryOptions>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>True</optional>
      <locations>
        <sourceRange category="necessary">
          <revisionRange>
            <introduced>94fe792df46e64f438720295742b3b72c407cab6</introduced>
            <removed>1ed40f72e772adaa3adfcc94b9f038e4f3382339</removed>
          </revisionRange>
          <path>main.c</path>
          <start>
            <line>6</line>
            <column>3</column>
          </start>
          <end>
            <line>6</line>
            <column>26</column>
          </end>
        </sourceRange>
        <sourceRange category="necessary">
          <revisionRange>
            <introduced>a7fb445f986adb2c2972df337ea46930cfc3dbf2</introduced>
          </revisionRange>
          <path>main.c</path>
          <start>
            <line>6</line>
            <column>3</column>
          </start>
          <end>
            <line>6</line>
            <column>26</column>
          </end>
        </sourceRange>
      </locations>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
  <booleanConstraints/>
</vm>

=== se-sic/vara-feature/unittests/resources/test_missing_root.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="Children" root="test">
  <binaryOptions>
    <configurationOption>
      <name>CB</name>
      <parent>C</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CA</name>
      <parent>C</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>root</name>
      <children>
        <options>A</options>
        <options>B</options>
        <options>C</options>
      </children>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>CC</name>
      <parent>C</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
  <booleanConstraints/>
</vm>

=== se-sic/vara-feature/unittests/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="ABC" root="test">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>False</optional>
      <location>
        <path>main.c</path>
        <start>
          <line>6</line>
          <column>3</column>
        </start>
        <end>
          <line>6</line>
          <column>26</column>
        </end>
      </location>
    </configurationOption>
    <configurationOption>
      <name>AA</name>
      <parent>A</parent>
      <excludedOptions>
        <options>AC</options>
        <options>C</options>
      </excludedOptions>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>AB</name>
      <parent>A</parent>
      <excludedOptions>
        <options>AC</options>
      </excludedOptions>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>AC</name>
      <parent>A</parent>
      <excludedOptions>
        <options>AA</options>
        <options>AB</options>
      </excludedOptions>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>C</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions>
    <configurationOption>
      <name>N</name>
      <parent>B</parent>
      <optional>True</optional>
      <values>1;5;9</values>
    </configurationOption>
  </numericOptions>
  <booleanConstraints>
    <constraint>!N | C</constraint>
    <constraint>!AA | !AB</constraint>
    <constraint>!AB | B</constraint>
    <constraint>!B | AB</constraint>
    <constraint>AB | AC | AA</constraint>
  </booleanConstraints>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_member_offset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="Children" root="test">
  <binaryOptions>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>True</optional>
      <locations>
        <sourceRange category="necessary">
          <path>main.c</path>
          <start>
            <line>6</line>
            <column>3</column>
          </start>
          <end>
            <line>6</line>
            <column>26</column>
          </end>
          <memberOffset>
            className::methodName
          </memberOffset>
        </sourceRange>
      </locations>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
  <booleanConstraints/>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_only_children.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="Children" root="test">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <children>
        <options>A</options>
        <options>B</options>
        <options>C</options>
      </children>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>C</name>
      <children>
        <options>CA</options>
        <options>CB</options>
        <options>CC</options>
      </children>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CA</name>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CB</name>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>CC</name>
      <optional>True</optional>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
  <booleanConstraints/>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_with_whitespaces.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<vm name="ABC" root="test">
  <binaryOptions>
    <configurationOption>
      <name>   root</name>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A   </name>
      <parent>
      </parent>
      <optional>False</optional>
    </configurationOption>
  </binaryOptions>
</vm>

=== se-sic/vara-feature/unittests/resources/xml/test_non_existent_implication.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vm SYSTEM "vm.dtd">
<!--Model is intentionally broken!-->
<vm name="Children" root="test">
  <binaryOptions>
    <configurationOption>
      <name>root</name>
      <children>
        <options>A</options>
        <options>B</options>
        <options>C</options>
      </children>
      <optional>False</optional>
    </configurationOption>
    <configurationOption>
      <name>A</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <name>B</name>
      <parent>root</parent>
      <optional>True</optional>
    </configurationOption>
    <configurationOption>
      <!--implied option MISSING does not exist-->
      <name>C</name>
      <parent>root</parent>
      <optional>True</optional>
      <impliedOptions>
        <options>MISSING</options>
      </impliedOptions>
    </configurationOption>
  </binaryOptions>
  <numericOptions/>
  <booleanConstraints/>
</vm>
